Web UI
SURFnet/eduhub-validator-service pull request #15
Opened 2024-10-12 11:41 UTC by mdemare

- **View status**
- **Removed wrap-routes**
- **Last fixes**

2024-10-23 12:09 UTC, joodie requested changes

2024-10-23 12:09 UTC, joodie commented on src/nl/surf/eduhub/validator/service/jobs/status.clj
> +      (let [m (into {} (apply hash-map result))
`hash-map` geeft al een map terug.

2024-10-23 12:09 UTC, joodie commented on src/nl/surf/eduhub/validator/service/jobs/status.clj
> +            m (into {} (for [[k v] m] [(keyword k) v]))]
nieuwere clojure versies hebben `update-keys` hiervoor.

dus dan wordt het iets als

```clojure
(when-not (empty? result)
      (update-keys keyword (apply hash-map result))
```

2024-10-23 12:09 UTC, joodie commented on src/nl/surf/eduhub/validator/service/jobs/status.clj
> +        (assert (every? keyword? (keys m)))
Volgens mij is er geen mogelijke situatie waar deze assert faalt

2024-10-23 12:33 UTC, mdemare commented on src/nl/surf/eduhub/validator/service/authentication.clj
> +    (let [{:keys [client-id public] :as resp} (app request)]
`wrap-authentication` wordt als eerste uitgevoerd, dus er is nog niks gebeurd, behalve de routing. Ik heb de middleware expres zo geschreven dat ze als eerste (app request) uitvoeren, om het geheel wat minder onoverzichtelijk te maken.

2024-11-05 09:14 UTC, joodie approved these changes

2024-11-05 09:26 UTC, merged